### ISSUE TITLE
[Enchantment] Add a timestamp for a song in Last Played list.

### ISSUE THREAD

**Issue by xTheEc0** [LISTEN-moe/android-app#15]
Add a timestamp for a song in Last Played list.

My reasoning is that sometimes when the WebSocket shits itself and doesn't update the name of the song anymore, it might be hard to notice if the song name has changed. Having some kind of indicator of what and when happened would help?

**Comment by arkon** [comment]
The websocket data doesn't readily have this. It's technically possible to calculate based on the current song's start time and past songs' durations (if they're not 0), but I'd rather try to fix the root cause instead (#17).
