### ISSUE TITLE
Sleep timer number max increase/sleep clock off

### ISSUE THREAD

**Issue by ZaneHannanAU** [LISTEN-moe/android-app#16]
Current version: 2.0.4/Android

* current:

  ![current appearance](https://i.imgur.com/ZWKF0ZS.png)
* possible alternate appearance select:

  ![possible alternate appearance select](https://i.imgur.com/Pjk0ql6.png)
* clock off variant:

  ![hr](https://i.imgur.com/29wBm2v.png)

  ![min](https://i.imgur.com/Trx206u.png)

basically just increase the numbers for countdown and have well set optional definited times in clock off select variant.

sorry for bad \* late night reports aren't my forte

**Comment by arkon** [comment]
Limit was increased to 2 hours in e77e6611d48b4915ad01b49e04eaf453d2137031.

I still need to think about what a better design would be.
