### ISSUE TITLE
Song title is not updating

### ISSUE THREAD

**Issue by Nikolay0054** [LISTEN-moe/android-app#17]
**Please describe the problem you are having in as much detail as possible:**

I have unstable network. When it laggs I have 'timeout' sign and song title stops updating but music is playing. Restarting app helps

**Further details:**

- App version: 3.0.3
- Android version: 8.1, LineageOS
- Device: Xiaomi Redmi Note 4
- Priority this should have – please be realistic and elaborate if possible: High

**Comment by arkon** [comment]
> @arkon 👻  - Could randomly losing connection (song info doesn't update) and failing to connect at all (audio plays tho) be related? If so, maybe with my simple repro you could fix half the issues : ^ )
>
>Turn off network on the device completely
>Open player, says no network. all gucci thats expected.
> Turn on network and press CONNECT
you can now play audio but song name or album cover is not displayed.

**Comment by arkon** [comment]
Partially fixed in v5 (for jpop at least).

**Comment by techies4president** [comment]
Still happening, but only when I am not logged in. 
Android 8.1, Moto G5, LTE 
My workaround is to log in only to set *favourite* and log off after it.
