### ISSUE TITLE
Upload betas to Google Play beta channel

### ISSUE THREAD

**Issue by CaesarW** [LISTEN-moe/android-app#29]
Just checked last update date on Google Play and it's... Sept. 2018??

I've seen lots of commits since Sept. 2018 and some of them are labeled as 5.0.0-beta. So there's version 5.0.0 coming right?

I know these betas may be very unstable and even malfunctioning, but is it possible to upload these beta builds to F-droid or Google Play beta channel, or just GitHub release page?

I think there would be a lot of people expecting to get fresh updates from there.

**Comment by iCrawl** [comment]
![](https://i.imgur.com/iZn7d4x.jpg)

They are being uploaded to the beta channel, just unsure if you can sign up publicly for it.

**Comment by CaesarW** [comment]
Oh.. seems like I'm not able to get enrolled in beta channel.
I'm not using the official Google play app for downloading. I am using Aurora store. And probably it's because Aurora store can't detect whether a beta channel is full or not.

Any ways to get betas on F-droid?

**Comment by CaesarW** [comment]
Confirmed. Should be the issue of Aurora store.
What about just attach beta builds to GitHub release page and label as PRE-RELEASE?

**Comment by arkon** [comment]
It's a public beta via the Google Play Store, but I honestly haven't gotten v5 up to a decent enough point to release to stable yet.

**Comment by CaesarW** [comment]
@arkon thanke, just confirmed that it's Aurora store's issue. Now joined beta channel.
Thanks for help!
