### ISSUE TITLE
Add Create playlist and Close feature in the Listen.moe app: j-pop and anime music radio

### ISSUE THREAD

**Issue by ammarraisafti** [LISTEN-moe/android-app#30]
# Components 
Listen moe is an open source app for listening to music on android devices, which is listening to j-pop music via Tune radio. Users can search for the desired song, then play it, and support bluetooth, also headphones control. It looks very clean, so it's easy to use. The problem is that developers do not provide the "Create Playlist" feature and the "Close" feature.

# Proposal
* Propose "Create Playlist" feature in Listen moe app. We recommend that developers add those features / shortcuts in the Tune radio section, and modify the Users menu section to provide a "create playlist" page. And add two choices of features in the section, namely the choice of "Frequently played and Recently played". And grant permission to add j-pop music currently playing, by clicking on the shortcut icon add new list in the Tune radio section.

* Propose the "Close" feature in the moe Listen app, add the feature in the notification / status bar of the android device, when j-pop music is being played. And gives the user access to eliminate notifications and turn off the music being played using the feature.

# Mockups /  Examples
**Create Playlist**
* An example image in the Tune radio section, after the developer added the "Add playlist" feature / shortcut.
![Screenshot_20180301-105137-picsay.png](https://cdn.utopian.io/posts/6a3958278d28e3fb7b89a0a691a4dd8fdd70Screenshot_20180301-105137-picsay.png)

* An example image after the developer modifies the User menu section to provide a "Create Playlist" page. Then add features "Frequently played and Recently played" in the section.
![Screenshot_20180301-105137-picsay.png](https://cdn.utopian.io/posts/abb8b3b4018cfb8f59ab107ddfc004043787Screenshot_20180301-105137-picsay.png)

* An example of the resulting image, after modification is complete.
![Screenshot_20180301-105137-picsay.png](https://cdn.utopian.io/posts/f63b923454c7bf9f19fcbaf631e76b217a3dScreenshot_20180301-105137-picsay.png)

* Sample image after user adds j-pop music to Frequently played playlist.
![Screenshot_20180301-105137-picsayhsha.png](https://cdn.utopian.io/posts/b9d381149f758ac0126fb14434485ca0badfScreenshot_20180301-105137-picsayhsha.png)

* Sample image after user adds j-pop music to Recently played playlist.
![Screenshot_20180301-105137-picsaygvv.png](https://cdn.utopian.io/posts/d2205d2d0a7ef811a064dfcd1041645e287cScreenshot_20180301-105137-picsaygvv.png)

**Close**
* An example image in the device status bar notification section, before the developer adds a "Close / icon shortcut" feature.
![Screenshot_20180301-105137-picsay.png](https://cdn.utopian.io/posts/dc8a33c22f81ef4594157bbdf722075950d3Screenshot_20180301-105137-picsay.png)

* An example image in the device status bar notification section, after the developer adds a "Close / icon shortcut" feature.
![Screenshot_20180301-105137-picsay.png](https://cdn.utopian.io/posts/fa89d728960c8a59add02e6e0d9ecbde8198Screenshot_20180301-105137-picsay.png)

# Benefits
* With the "Create Playlist" feature in the Listen moe app, users can create playlists of j-pop music that they listen to on Tune radio. And add the music to the Frequently Placed folder and to the Recently played folder. And can play j-pop music that has been added by them, at the desired time, so no trouble to find the j-pop music.

* With the "Close / icon shortcut" feature in the status bar notification section, users will be able to turn off the music, without having to enter the Listen moe app. And can eliminate ongoing notifications, when j-pop music is being played.

**Comment by arkon** [comment]
@ammarraisafti The images don't work.

Regarding the close functionality, this app follows the typical UX model of pausing and swiping the notification away.
