### ISSUE TITLE
Latest version contains nonfree google libraries

### ISSUE THREAD

**Issue by Bubu** [LISTEN-moe/android-app#39]
The latest version published on F-Droid somehow contains nonfree google libraries, you can find some more details here: https://gitlab.com/fdroid/fdroiddata/-/issues/2070

**Comment by Bubu** [comment]
I'd like to go ahead and disable the affected version in F-Droid (which would make the 5.0.0-rc.3 it seems availableas latest in F-Droid).
Or are you planning to release a new version in the next few days, in which case I think we'd be  okay with waiting until that is available.

**Comment by arkon** [comment]
I just tagged a new release: https://github.com/LISTEN-moe/android-app/releases/tag/v5.2.0

**Comment by Bubu** [comment]
Thanks for the super quick turnaround. I've disabled the old version and added the new one to f-droid.

**Comment by ygsk10** [comment]
Excause me, am I the only one finding the latest release on F-Droid is not signed by any keys?(so that cannot be installed

**Comment by arkon** [comment]
@ygsk10 Open an issue with F-Droid if you're having issues with it.
