### ISSUE TITLE
"UNFAVORITE" doesn't fit into the screen and gets clipped

### ISSUE THREAD

**Issue by xTheEc0** [LISTEN-moe/android-app#46]
**Please describe the problem you are having in as much detail as possible:**
The word 'unfavorite' gets clipped in portrait mode.

**Further details:**
I am assuming this is only for some resolutions/aspect ratios, don't have more phones with me atm to test out.

- App version: 5.2.2
- Android version: 10
- Device: OnePlus 7 Pro
- Priority this should have – please be realistic and elaborate if possible: LOW  

![Screenshot_20201228-034839](https://user-images.githubusercontent.com/24303281/103184315-45fc1080-48c0-11eb-9d3d-af688c9ee89d.jpg)
![Screenshot_20201228-034942](https://user-images.githubusercontent.com/24303281/103184317-4a282e00-48c0-11eb-9392-58fea91dfa64.jpg)
![Screenshot_20201228-034947](https://user-images.githubusercontent.com/24303281/103184320-4c8a8800-48c0-11eb-83e6-f1fb07c35c65.jpg)

**Comment by arkon** [comment]
Fixed by #48
