### ISSUE TITLE
Application doesn't stop when headphones get unplugged

### ISSUE THREAD

**Issue by Shumatsu** [LISTEN-moe/android-app#5]
I have a habit of unplugging headphones instead of pausing music apps properly, so I noticed that the app doesn't pause when you unplug the headphones. You can't close the notification control panel if that happens. What's worse,  it used 259MB of data today, while I listened for something like 30 minutes. That's about 6 times more than a 192kbps cbr audio stream would take. All that data and resources on both sides wasted for something I wasn't using.

**Comment by iCrawl** [comment]
I just listened to it today while walking to work. Unplugged the headphones, checked the notification center and it was paused.

Afterwards I just closed the app as usual via the overview.

**Comment by Pitu** [comment]
Just tried it, the app pauses just fine. Check you're on the latest version and try opening the app with your headphones plugged in > pressing play > unplugging headphones and let us know if it works as intended.

**Comment by iCrawl** [comment]
Also maybe mention android version, app version (if possible) and phone 🤔

**Comment by arkon** [comment]
Also check if the setting is enabled (assuming you're on the latest version).

**Comment by Shumatsu** [comment]
I can't replicate the bug now. I guess that was one off instance of this happening. Probably my phone's fault, actually.

App version: 1.4.0
Android Version: 6.0
Phone: HTC U Play
Software number: 1.30.401.4
