### ISSUE TITLE
[Setup Flaw] The app stops playing music while the screen is off

### ISSUE THREAD

**Issue by Ryu945** [LISTEN-moe/android-app#52]
**The app stops playing music while the screen is off**

**If you have ever played a video in an android web browser using Invidious, your notice that you can turn off the screen and it still continues to play the the video.  This is true even if battery optimization is turned on for the web browser.   With Listen.moe, it will not play music with the screen off unless you turn off battery optimization.   Can you change the implementation so that that it works more like playing a video with Invidious on the web browser.**

- App version: 5.4.2 (From Fdroid Store)
- Android version: 11
- Device: LG V20
- Priority this should have – please be realistic and elaborate if possible: Low priority since there is a work around but people have to know how to turn on the work around.   It also causes increased battery drain.

**Comment by Ryu945** [comment]
This is still not fixed.

**Comment by FluffyDiscord** [comment]
Any updates on this? The app is set in settings as "unrestricted" battery usage. Any other apps is "fixed" with this setting.

**Comment by arkon** [comment]
This is improved with the work in #56, so I'll close this. Otherwise, https://dontkillmyapp.com/ is applicable.
