### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by Porkepix** [LISTEN-moe/android-app#6]
Currently the app is only available through the Google Play Store.

It could be nice to also distribute it by providing apks here, as release on GitHub.
Another place that could also be nice to provide those is on F-droid (https://f-droid.org/), an alternative store including only free softwares (as in freedom).

Some users are not that much fond of Google and the Play Store or can even have a phone without it (for example if they use Lineage OS), and this would allow them to use this application.

**Comment by arkon** [comment]
The app will eventually include Play Services for casting support, so I'm not sure if I'll be building different variants for that yet for F-droid. I'll consider running some sort of CD pipeline to publish APKs.

**Comment by Porkepix** [comment]
What do you mean by "casting support" here? I don't get the kind of features you have in mind.

**Comment by arkon** [comment]
Chromecast support.

**Comment by Porkepix** [comment]
I don't know that well about how this kind of support is done. Does this absolutely need Play services? Isn't this working as local network service on a Wi-Fi?
If this presence is absolutely required, maybe this could be an additional/optional feature only present on Play Store builds? (Through build options/flags?)

**Comment by arkon** [comment]
It does require Play Services, otherwise it requires a lot of extra effort (which is why VLC is still working on it, I believe).

The build flavours would be a way to publish versions without the feature, which I'll likely do anyway for the Amazon version as well.

**Comment by arkon** [comment]
Submitting: https://gitlab.com/fdroid/rfp/issues/443

**Comment by relan** [comment]
Hi,

F-Droid maintainer here. LISTEN.moe builds and works for me (`fdroid` flavor), it can be added as is, but I'd like to set up automatic updates. There are two issues preventing this:

1. No Git tags. Tags are the only reliable way to know whether there is a new version.
2. Version name has " (F-Droid)" suffix. F-Droid server needs to deduce version name from Git tag and it cannot add anything to it.

**Comment by arkon** [comment]
@relan Thanks! I've set up git tags and removed the suffix (in v1.6.4). Let me know if there's any other action items on my end.

**Comment by relan** [comment]
Should be available in a few days, thanks!

**Comment by arkon** [comment]
Hey @relan, it doesn't seem like it's shown up in the F-Droid repo yet. Is there something that needs to be done?

**Comment by relan** [comment]
F-Droid build server currently has stability problems. No ETA, unfortunately.

**Comment by Porkepix** [comment]
Hi, first of all, thanks for the work to have it available on F-droid, even though it's not there yet (backlog is shrinking after issues they got, but it takes some time).

I was discussing a bit with people from F-droid on IRC about this issue and wanted to check something about listen.moe app and thought it wasn't listed: I was actually tricked by the package id as it didn't contain the app name at all. Out of curiosity, is this some choice for whatever reason?

**Comment by arkon** [comment]
It was originally `me.echeung.listenmoe` (or something along those lines) but it got banned from Google Play because it was "impersonating the website" (...or something along those lines), so I had to change it and I just went with a cute reference.

What do you mean when you were "tricked" by the package id though?

**Comment by Porkepix** [comment]
Well, just that I looked at the current backlog of builds undergoing here: https://f-droid.org/wiki/page/Category:Apps_with_failing_builds and dumbly ctrl-f'ed with "listen". I've got no match so I said to the guy I was talking with on #fdroid that listen.moe was not listed.
Then he asked for the package id, I looked after it in the F-droid issue tracker and realized I didn't searched for the right string and that it was correctly listed.
Intuitively I would have think about getting listen[.]moe somewhere in the id.

**Comment by arkon** [comment]
I see. Unfortunately, I don't intend on ever changing the id in the future unless it gets banned from Google Play again.

**Comment by relan** [comment]
Here's the info page: https://f-droid.org/wiki/page/me.echeung.moemoekyun.fdroid

There was a bug in fdroidserver when it didn't even try to build some apps. It has been [recently fixed](https://gitlab.com/fdroid/fdroidserver/commit/9a4f3ac019d3dc3d9154db6b434f717623c4c0e2). Currently there are 137 apps to build---down from 155 two days ago. So one day all of them will be built.

**Comment by arkon** [comment]
It's available on F-Droid now, although it's a few versions behind right now.

https://f-droid.org/packages/me.echeung.moemoekyun.fdroid/
