### ISSUE TITLE
Why is F-droid behind with versions?

### ISSUE THREAD

**Issue by inson1** [LISTEN-moe/android-app#62]

**Comment by arkon** [comment]
I don't actually know, I was under the impression F-Droid is supposed to get updates automatically based on the GitHub repo: https://f-droid.org/docs/FAQ_-_App_Developers/#do-i-need-to-tell-you-when-i-update

Could probably manually update https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/me.echeung.moemoekyun.fdroid.yml?blame=0 if that's broken on their side.

**Comment by inson1** [comment]
@licaon-kter hey dont you know what is up with it? Main develoloeper also doesnt know

**Comment by licaon-kter** [comment]
Will test locally, odd indeed

**Comment by arkon** [comment]
Thanks!
