### ISSUE TITLE
[Feature?] Seing more played songs and ability to star them.

### ISSUE THREAD

**Issue by xTheEc0** [LISTEN-moe/android-app#7]
This is a pretty specific use-case, but I usually listen to the radio when I am driving.
And that means I usually can't favourite/star a song (unless I'm at a red light or smt)
Also, only the last 2 played songs can be seen making this even worse ;...;

Yes, technically I can manually search the song and favorite it BUT, yet again I can only see 2 last songs, and most of the time the name will be in kana not in romaji/english, so entering is quite difficult  😱 

Doing (expandable?) list of 5~ and having an ability to star them would be 👌 

Thanks : )

**Comment by iCrawl** [comment]
This should probably be discussed here: https://github.com/LISTEN-moe/feedback

Arkon could theoretically expand it himself by saving the last played songs and extending them himself, but if you want to be able to have this across all devices and services you should definitely post that there to open a discussion about it.

**Comment by arkon** [comment]
Can favourite from the last played dialog in v3.0.0-alpha.12.
