### ISSUE TITLE
Chinese Simplified translation

### ISSUE THREAD

**Issue by CaesarW** [LISTEN-moe/android-app#8]
Hello!

The first version of Chinese translation has been completed. Please merge the translation in order to let me do some further language localization.

BTW: Great app!

**Comment by arkon** [comment]
Thanks! I'll merge it in soon, but I'm also working on an update so I'll be adding more phrases on OneSky soon.

**Comment by arkon** [comment]
Updated OneSky with new strings.

**Comment by arkon** [comment]
Just published a new alpha version (v3.0.0-alpha.6) with the translations included.

If you're not already in the alpha/beta testing program, you can [join here](https://play.google.com/apps/testing/me.echeung.moemoekyun).
