### ISSUE TITLE
Scrolling to the ends of 'Last Played' list jitters.

### ISSUE THREAD

**Issue by xTheEc0** [LISTEN-moe/android-app#9]
**Please describe the problem you are having in as much detail as possible:**
Scrolling to the ends of 'Last Played' list jitters.  
This might be default Android behaviour, but I am unsure, so might as well report it.

Video: https://puu.sh/A8TTf/1cb2d1b83e.mp4   
(ignore the weird ass cropping. `adb shell screenrecord` magic..)  

**Further details:**  
- App version: 3.0.0-alpha.13
- Android version: Android 7.0
- Device: Samsung Galaxy S7 SM-G930F 
- Priority: Low

**Comment by arkon** [comment]
_Should_ be fixed in 3.0.0-alpha.14.
